---
title: "Fruit  files"
author: "Olachi Mbakwe,William Bevidas"
date: "2023-10-31"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	include=FALSE
)

```



```{r}

# Load packages
packages <- c("tidyverse", "knitr","dplyr", "kableExtra","parameters", "emmeans", "DescTools","dunn.test", "multcompView")



lapply(
  X = packages,
  FUN = library,
  character.only = TRUE
)


# Set options
options(knitr.kable.NA = "")


# Load additional tools
source("https://raw.github.com/neilhatfield/STAT461/master/rScripts/ANOVATools.R")

```

type 1 error is point


```{r  Loading data}

fruitflies <- read_csv("fruitflies.csv")

### Set year to an ordered factor
fruitflies$condition <- factor(
x = fruitflies$condition,
levels = c("Null", "One Pregnant", "One Virgin","Eight Pregnant","Eight Virgin")
)

```


```{r}
modelLabels <- c("1 Reproduction 1", "5 Reproduction Condition 4", "125 (Male Fruit Flies) 120")
modelMatrix <- matrix(
  data = c(FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE),
  nrow = 3,
  ncol = 3,
  byrow = FALSE
)
hasseDiagram::hasse(
 data = modelMatrix,
 labels = modelLabels
)
```


